<?xml version="1.0" encoding="utf-8"?><Database Name="ELIXIR" Class="RxOutletDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-DDIP9VH\SQLEXPRESS;Initial Catalog=ELIXIR;Integrated Security=True;Persist Security Info=True" SettingsObjectName="RxOutlet.DataAccess.Properties.Settings" SettingsPropertyName="ELIXIRConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblMainMenu" Member="tblMainMenus">
    <Type Name="tblMainMenu">
      <Column Name="MenuID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MenuName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Association Name="tblMainMenu_tblMenuItem" Member="tblMenuItems" ThisKey="MenuID" OtherKey="MenuID" Type="tblMenuItem" />
      <Association Name="tblMainMenu_tblSubMenus" Member="tblSubMenus" ThisKey="MenuID" OtherKey="MenuID" Type="tblSubMenus" />
    </Type>
  </Table>
  <Table Name="dbo.tblMenuItems" Member="tblMenuItems">
    <Type Name="tblMenuItem">
      <Column Name="MenuItemID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MenuItemName" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="MenuID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SubMenuID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tblMainMenu_tblMenuItem" Member="tblMainMenu" ThisKey="MenuID" OtherKey="MenuID" Type="tblMainMenu" IsForeignKey="true" />
      <Association Name="tblSubMenus_tblMenuItem" Member="tblSubMenus" ThisKey="SubMenuID" OtherKey="SubMenuID" Type="tblSubMenus" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblSubMenus" Member="tblSubMenus">
    <Type Name="tblSubMenus">
      <Column Name="SubMenuID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SubMenuName" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="MenuID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tblSubMenus_tblMenuItem" Member="tblMenuItems" ThisKey="SubMenuID" OtherKey="SubMenuID" Type="tblMenuItem" />
      <Association Name="tblMainMenu_tblSubMenus" Member="tblMainMenu" ThisKey="MenuID" OtherKey="MenuID" Type="tblMainMenu" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Druginfo" Member="Druginfos">
    <Type Name="Druginfo">
      <Column Name="DrugId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DrugName" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="SupplierID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SupplierName" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="RetailPrice" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="RegularPrice" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Association Name="Supplier_Druginfo" Member="Supplier" ThisKey="SupplierID" OtherKey="SupplierID" Type="Supplier" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Suppliers" Member="Suppliers">
    <Type Name="Supplier">
      <Column Name="SupplierID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SupplierName" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Association Name="Supplier_Druginfo" Member="Druginfos" ThisKey="SupplierID" OtherKey="SupplierID" Type="Druginfo" />
    </Type>
  </Table>
  <Function Name="dbo.GetSupplierName" Method="GetSupplierName">
    <ElementType Name="GetSupplierNameResult">
      <Column Name="SupplierId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Suppliername" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="drugcount" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetDrugNamesSearch" Method="GetDrugNamesSearch">
    <ElementType Name="GetDrugNamesSearchResult">
      <Column Name="SupplierID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SupplierName" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="DrugID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ImageNum" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="DrugName" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetDrugTypes" Method="GetDrugTypes">
    <ElementType Name="GetDrugTypesResult">
      <Column Name="DrugTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DrugTypeName" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="drugcount" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetMenu" Method="GetMenu">
    <ElementType Name="GetMenuResult">
      <Column Name="MainMenuID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MainMenuName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="SubMainMenuID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SubMenuID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SubMenuName" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="ItemMainMenuID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ItemSubMenuID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MenuItemID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MenuItemName" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetProductDetails" Method="GetProductDetails">
    <Parameter Name="DrugID" Parameter="drugID" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetProductDetailsResult">
      <Column Name="Drugname" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="SupplierName" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="RetailPrice" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="RegularPrice" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="drugtypename" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="ImageNum" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetDrugList" Method="GetDrugList">
    <ElementType Name="GetDrugListResult">
      <Column Name="ImgNum" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="DrugId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DrugName" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="RetailPrice" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="RegularPrice" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>